version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
      ruby: 2.6
    commands:
      - apt-get update
      - apt-get install -y build-essential software-properties-common
      - apt-add-repository -y ppa:brightbox/ruby-ng
      - apt-get update
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: 
    - '**/*'